version: '2.1'

services:
  spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    hostname: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    hostname: spark-worker-2
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
